### ISSUE TITLE
Use Middleware in Group

### ISSUE THREAD

**Issue by zulkifliraihan** [atayahmet/express-route-grouping#3]
How To Use Middleware in Group?

`const location = new RouteGroup('/location', route)
location.group('/', loc => {
    loc.use(JWTMiddleware)
    const locationService = new LocationService(locationRepository)
    const locationController = new LocationController(locationService)

    
    loc.get('/country', locationController.getDataCountry.bind(locationController))
    loc.get('/state', locationController.getDataState.bind(locationController))
    loc.get('/state/:countryId', locationController.getDataStateByCountryId.bind(locationController))
    loc.get('/city', locationController.getDataCity.bind(locationController))
    loc.get('/city/:stateId', locationController.getDataCityByStateId.bind(locationController))
    loc.get('/timezone/:countryId/', locationController.dataTimezoneByCountryId.bind(locationController))
})`

Error :
/node_modules/express-route-grouping/src/index.ts:69
    let newPath = path.replace(/^(\/+)(.)/, '$2').replace(/(.)(\/+)$/, '$1');
                       ^
TypeError: path.replace is not a function

**Comment by atayahmet** [comment]
Hi @zulkifliraihan, 

I have released the new version. Please check it out
